# Generated by Django 5.0.4 on 2024-04-23 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_remove_song_albums_remove_artist_userprofile_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artist_name', models.CharField(max_length=100, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myApp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_uri', models.CharField(default='default.png', max_length=255)),
                ('like_count', models.IntegerField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_uri', models.CharField(default='default.png', max_length=255)),
                ('uri', models.CharField(max_length=255, unique=True)),
                ('like_count', models.IntegerField()),
                ('genres', models.CharField(choices=[('POP', 'Pop'), ('ROCK', 'Rock'), ('COUNTRY', 'Country'), ('RAP', 'Rap'), ('JAZZ', 'Jazz'), ('BLUES', 'Blues'), ('RNB', 'R&B'), ('HIPHOP', 'Hip Hop'), ('EDM', 'Electronic Dance Music'), ('CLASSICAL', 'Classical'), ('REGGAE', 'Reggae'), ('HEAVY_METAL', 'Heavy Metal'), ('FOLK', 'Folk'), ('SOUL', 'Soul'), ('PUNK', 'Punk'), ('ALTERNATIVE', 'Alternative'), ('INDIE', 'Indie'), ('OTHER', 'Other')], default='Other', max_length=255)),
                ('albums', models.ManyToManyField(related_name='songs', to='myApp.album')),
                ('playlists', models.ManyToManyField(related_name='songs', to='myApp.playlist')),
            ],
        ),
    ]
